### ISSUE TITLE
LispWorks 6.1 error in get-node-id on linux: "Cannot have / in a top-level directory name"

### ISSUE THREAD

**Issue by Wz5m165c** [dardoria/uuid#5]
With LispWorks 6.1, calling `make-v1-uuid` signals an error "Cannot have / in a top-level directory name".

This seems to be because `make-pathname :directory` shouldn't contain names with `/`-character. For more information, see http://www.lispworks.com/documentation/lw50/CLHS/Body/19_bbdc.htm: "Each string names a single level of directory structure. The strings should contain only the directory names themselves---no punctuation characters." or Edi Weitz's and Rainer Joswig's commentary here: http://coding.derkeiler.com/Archive/Lisp/comp.lang.lisp/2007-09/msg00914.html.

This patch seems to fix the issue:

```diff
diff --git a/uuid.lisp b/uuid.lisp
index a2494f8..eab0509 100644
--- a/uuid.lisp
+++ b/uuid.lisp
@@ -100,10 +100,10 @@ characters.~@:>" string (length string)))
                                                  (directory "/sys/class/net/*/"))
                                          :test #'equal))))
            (when (not (null interface))
-             (with-open-file (address (make-pathname :directory
+             (with-open-file (address (make-pathname :defaults
                                                      (concatenate 'string
                                                                   "/sys/class/net/"
-                                                                  interface)
+                                                                  interface "/")
                                                      :name "address"))
                (parse-integer (remove #\: (read-line address)) :radix 16))))
```

**Comment by dardoria** [comment]
Thanks for reporting this.

Can you open a pull request and I will merge it - I don't have access to LispWorks (or any other Lisp) at the moment?

Also I think that something like `(make-pathname :directory '(:absolute "sys" "class" "net" interface)` would be better.

**Comment by dardoria** [comment]
Merged.
